import random
from typing import List, Sequence

DIAMOND = "♦"
CIRCLE = "O"
INFILTRATOR = "X"
EMPTY = "-"


def _build_symbol_pool() -> List[str]:
    """
    Creates the base list of symbols for a 5x5 card.

    Returns
    -------
    List[str]
        A list containing 6 diamonds, 5 circles, 1 infiltrator and 13 blanks.
    """
    return (
        [DIAMOND] * 6
        + [CIRCLE] * 5
        + [INFILTRATOR]
        + [EMPTY] * 13
    )


def generate_card(rng: random.Random | None = None) -> List[List[str]]:
    """
    Generate a random 5x5 card following the rules:
    - 6 diamonds (♦)
    - 5 circles (O)
    - 1 infiltrator (X)
    - Remaining spaces as blanks (-)

    Parameters
    ----------
    rng : random.Random | None
        Optional random number generator to make output reproducible.

    Returns
    -------
    List[List[str]]
        A 5x5 matrix of symbols.
    """
    rng = rng or random.Random()
    pool = _build_symbol_pool()
    rng.shuffle(pool)
    return [pool[i * 5 : (i + 1) * 5] for i in range(5)]


def format_card(card: Sequence[Sequence[str]]) -> str:
    """
    Formats a 5x5 card into a printable string.

    Parameters
    ----------
    card : Sequence[Sequence[str]]
        The card generated by :func:`generate_card`.

    Returns
    -------
    str
        A human-readable representation with rows separated by newlines.
    """
    return "\n".join(" ".join(row) for row in card)


if __name__ == "__main__":
    card = generate_card()
    print(format_card(card))
